"""empty message

Revision ID: 2255ebc09bdf
Revises: 62aa7015cfbe
Create Date: 2023-02-24 11:44:10.765908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2255ebc09bdf'
down_revision = '62aa7015cfbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worked', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('day', sa.Integer(), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worked', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.drop_column('day')
        batch_op.drop_column('month')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
