"""empty message

Revision ID: 4f8d3b22b160
Revises: ec57856f3b0d
Create Date: 2023-02-17 16:35:35.682300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8d3b22b160'
down_revision = 'ec57856f3b0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
