"""empty message

Revision ID: 62aa7015cfbe
Revises: f4a60581b3df
Create Date: 2023-02-24 11:41:55.889012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62aa7015cfbe'
down_revision = 'f4a60581b3df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
