"""empty message

Revision ID: a3617e6aecba
Revises: 1d0b87d2dae7
Create Date: 2023-02-13 23:05:11.665449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3617e6aecba'
down_revision = '1d0b87d2dae7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga', sa.Column('page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manga', 'page')
    # ### end Alembic commands ###
