"""empty message

Revision ID: 74264bd8d71f
Revises: db1228aa9353
Create Date: 2023-02-14 09:28:17.632297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74264bd8d71f'
down_revision = 'db1228aa9353'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
