"""empty message

Revision ID: 89fc12e300bd
Revises: b2f8ea2187cf
Create Date: 2023-03-03 12:33:54.843818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89fc12e300bd'
down_revision = 'b2f8ea2187cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worked', sa.Column('wage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worked', 'wage')
    # ### end Alembic commands ###
