"""empty message

Revision ID: a039b708b13d
Revises: 
Create Date: 2023-03-03 22:40:35.044409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a039b708b13d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worked', sa.Column('wage', sa.String(), nullable=True))
    op.drop_constraint('uq_worked_year', 'worked', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_worked_year', 'worked', ['year', 'month', 'day', 'user_id'])
    op.drop_column('worked', 'wage')
    # ### end Alembic commands ###
