"""empty message

Revision ID: 1d0b87d2dae7
Revises: dc9239cffef1
Create Date: 2023-02-12 11:39:15.537113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0b87d2dae7'
down_revision = 'dc9239cffef1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], name=op.f('fk_manga_voter_manga_id_manga')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_manga_voter_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'manga_id', name=op.f('pk_manga_voter'))
    )
    op.create_table('video_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_video_voter_user_id_user')),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name=op.f('fk_video_voter_video_id_video')),
    sa.PrimaryKeyConstraint('user_id', 'video_id', name=op.f('pk_video_voter'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_voter')
    op.drop_table('manga_voter')
    # ### end Alembic commands ###
