"""empty message

Revision ID: 6c1ce5f8a340
Revises: dfc98d93968d
Create Date: 2023-02-14 10:23:12.101800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1ce5f8a340'
down_revision = 'dfc98d93968d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
