"""empty message

Revision ID: ea67cb11be75
Revises: 29fbb9069389
Create Date: 2023-02-24 15:28:00.376934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea67cb11be75'
down_revision = '29fbb9069389'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
